name: conso2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  provider: ^6.1.2
  flutter_native_splash: ^2.4.1
  geolocator: ^10.1.0
  google_sign_in: ^6.2.1

  # HTTP requests para comunicaci√≥n con backend
  http: ^1.2.0

  # Cupertino Icons for iOS style
  cupertino_icons: ^1.0.8

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: true
  image_path: "assets/VotaConti.png"

# Flutter-specific configuration
flutter:
  uses-material-design: true
  assets:
    - assets/logo_uc.png
    - assets/google_logo.png
    - assets/VotaConti.png

# Flutter native splash configuration
flutter_native_splash:
  color: "#1E88E5"
  image: assets/logo_uc.png
  android: true
